package view;

// todas as classes e pacotes necessários para banco de dados jdbc
import com.mysql.cj.jdbc.Blob;
import controller.Usuariodao;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JOptionPane;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class FormCli extends javax.swing.JFrame {
    
    private FileInputStream foto;
    private int tamanho ; 
    
 
    public FormCli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textcpf = new javax.swing.JTextField();
        textemail = new javax.swing.JTextField();
        textcelular = new javax.swing.JTextField();
        textnome = new javax.swing.JTextField();
        cmbnivel = new javax.swing.JComboBox<>();
        btngravar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        btnnovo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textSenha = new javax.swing.JPasswordField();
        btnexcluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        textemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textemailActionPerformed(evt);
            }
        });

        btngravar.setText("Gravar");
        btngravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngravarMouseClicked(evt);
            }
        });

        jLabel1.setText("CPF:");

        jLabel2.setText("NOME:");

        jLabel3.setText("EMAIL::");

        jLabel4.setText("CELULAR:");

        btnbuscar.setText("Buscar");
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnnovo.setText("Novo");
        btnnovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnovoMouseClicked(evt);
            }
        });
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        jLabel5.setText("SENHA:");

        btnexcluir.setText("Excluir");
        btnexcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexcluirMouseClicked(evt);
            }
        });

        jLabel6.setText("Selecione Nível:");

        btnFoto.setText("Carregar Foto");
        btnFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFotoMouseClicked(evt);
            }
        });
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(134, 134, 134)
                        .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textemail, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(textSenha)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbnivel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textnome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnbuscar))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btngravar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnnovo)
                    .addComponent(btnexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnbuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbnivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btngravar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "cpf", "nome", "email", "celular"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carregar_usuarios() {
        // método criado para carregar usuaŕios no jtable 
        // do formulário de usuários

        // captura o modelo definido do jtable no formulário de usuários
        DefaultTableModel mytbmodel = (DefaultTableModel) jTable1.getModel();

        // instancia a classe Usuariodao para executar o método buscartodos()
        Usuariodao u1 = new Usuariodao();

        // chama o método para buscar todos os registros da tabela usuário
        // armazena dentro de um objeto ResultSet
        ResultSet resul = u1.buscartodos();
        try {

            // apagar todas as linhas do Jtable
            while (jTable1.getModel().getRowCount() > 0) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
            }

// laço para pegar os registros retornadas na ResultSet resul
            while (resul.next()) {
                // cria um array para armazenar cada linha com os 4 campos
                // puxados da tabela resul de usuários

                Object[] linhas = {resul.getString("cpf"),
                    resul.getString("nome"),
                    resul.getString("email"),
                    resul.getString("celular")};

                // adiciona uma linha de cada vez no jtable de usuaŕios
                mytbmodel.addRow(linhas);
            }

            // posiciona o focus no textcpf 
            this.textcpf.grabFocus();
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }

    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

// captura o modelo do combobox para inserir itens
        DefaultComboBoxModel mymodel = (DefaultComboBoxModel) this.cmbnivel.getModel();
        mymodel.removeAllElements(); // remove todos os elementos do combobox
        mymodel.addElement(""); // adiciona o primeiro elemento vazio
        mymodel.addElement("Operador"); // adiciona o item operador
        mymodel.addElement("Gerente"); // adiciona o item gerente
        mymodel.addElement("Cliente"); // adiciona o item cliente

        carregar_usuarios(); // chama o método carregar_usuarios para preencher o jtable  

        // carrega uma imagem da pasta imagens para o lblFoto do form
       String CaminhoDaImagem = "/imagens/Figura.jfif";
       this.carregar_imagem_autosize ( CaminhoDaImagem);
        
    }//GEN-LAST:event_formWindowOpened

    
    private void carregar_imagem_autosize(String CaminhoDaImagem ) {      
           /* Para imagens no disco rigito com path absoluto use
              ImageIcon  imagem = new ImageIcon( "c:\temp\Figura.jpg" );
            
              Para imagens dentro do NetBeans com path relativo use 
              ImageIcon   imagem = new ImageIcon(getClass().getResource("/imagens/Figura.jfif")); */
           
            ImageIcon   imagem = new ImageIcon(getClass().getResource(CaminhoDaImagem));// Use este para path relativo        
            Image modelImagem = imagem.getImage();
            Image ModelEscalas = modelImagem.getScaledInstance(this.lblFoto.getWidth(), this.lblFoto.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ImagemAutoSize = new ImageIcon(ModelEscalas);
            this.lblFoto.setIcon ( null );
            this.lblFoto.setIcon(ImagemAutoSize);
  
    }

    private void btngravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngravarMouseClicked

        // insere a linha que será incluida no jtable usuários
        // instancia o objeto model Usuario 
        Usuario Lu = new Usuario();

        // preenche os atributos do objeto modelo Usuario
        Lu.setCpf(this.textcpf.getText());
        Lu.setNome(this.textnome.getText());
        Lu.setEmail(this.textemail.getText());
        Lu.setCelular(this.textcelular.getText());
        Lu.setIdNivel(this.cmbnivel.getSelectedIndex());
        Lu.setSenha(this.textSenha.getText());
 
        Lu.setFoto(this.foto);
        Lu.setTamanho(this.tamanho);
                
        
        // instancia o objedo Controller Usuariodao para executar gravar o registro
        Usuariodao u1 = new Usuariodao();

        // primeiro chama o método buscar para procurar o cpf na tabela
        ResultSet resul = u1.buscar(Lu);

        try {

            if (resul.next()) { // caso exista o cpf então chama u1.alterar()
                u1.alterar(Lu);
            } else {
                u1.incluir(Lu);// caseo não exista o cpf chama u1.incluir()
            }

        } catch (SQLException err) {

            JOptionPane.showMessageDialog(null, err.getMessage());
        }

        // captura o modelo do jtable para inserir linhas
        this.carregar_usuarios();
    }//GEN-LAST:event_btngravarMouseClicked

    private void textemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textemailActionPerformed

    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
        // instancia a classe Usuario model
        Usuario obj = new Usuario();
        // executa o método setcpf para preencher o cpf

        obj.setCpf(this.textcpf.getText());

        // instancia o objeto Controller Usariodao
        Usuariodao u1 = new Usuariodao();

        // executa o método buscar e coloca os registros dentro 
        // do ResultSet resul 
        ResultSet resul = u1.buscar(obj);

        try {
            if (resul.next()) {
                // se o registro foi encontrado preenche os campos do formulário usuários
                this.textnome.setText(resul.getString("nome"));
                this.textemail.setText(resul.getString("email"));
                this.textcelular.setText(resul.getString("celular"));
                this.cmbnivel.setSelectedIndex(resul.getInt("idnivel"));
                this.textSenha.setText(resul.getString("senha"));
            } else {
                JOptionPane.showMessageDialog(null, "Registro não encontrado!");
                this.textcpf.grabFocus();
            }

        } catch (SQLException err) {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnnovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnovoMouseClicked
        // preenche todos os campos do formulários usuaŕios com espaços em branco
        this.textcpf.setText("");
        this.textnome.setText("");
        this.textcelular.setText("");
        this.textemail.setText("");
        this.cmbnivel.setSelectedIndex(0);
        this.textcpf.grabFocus();

// TODO add your handling code here:
    }//GEN-LAST:event_btnnovoMouseClicked

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnexcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexcluirMouseClicked

        Usuariodao u = new Usuariodao();
        u.excluir(textcpf.getText());
        this.carregar_usuarios();


    }//GEN-LAST:event_btnexcluirMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int linhasel = this.jTable1.getSelectedRow(); // captura o numero da linha selecionada
        int colunachave = 0; // pega sempre o numero da coluna 0 

        // retorna sempre a primeira coluna da linha selecionada e armazena no objeto chave
        Object chave = this.jTable1.getModel().getValueAt(linhasel, colunachave);

        // seleciona pelo indice this.cmbnivel.setSelectedIndex(resul.getInt("idnivel"));
        // seleciona pelo item this.cmbnivel.setSelectedItem("Operador");
        // seleciona pelo numero da linha 
        // this.cmbnivel.setSelectedIndex(jTable1.getSelectedRow());
// instancia a classe Usuario model
        Usuario obj = new Usuario();
        // executa o método setcpf para preencher o cpf

        obj.setCpf((String) chave);

        // instancia o objeto Controller Usariodao
        Usuariodao u1 = new Usuariodao();

        // executa o método buscar e coloca os registros dentro 
        // do ResultSet resul 
        ResultSet resul = u1.buscar(obj);
        try {  if (resul.next()) {
                // se o registro foi encontrado preenche os campos do formulário usuários
                this.textcpf.setText(resul.getString("cpf"));
                this.textnome.setText(resul.getString("nome"));
                this.textemail.setText(resul.getString("email"));
                this.textcelular.setText(resul.getString("celular"));
                this.cmbnivel.setSelectedIndex(resul.getInt("idnivel"));
                this.textSenha.setText(resul.getString("senha"));
              
                /* Código que traz o arquivo de imagem no formato bytes do banco de dados  */
                Blob blob = (Blob) resul.getBlob(7);
                byte[] img = blob.getBytes(1, (int) blob.length());
                BufferedImage imagem = null;
                imagem = ImageIO.read(new ByteArrayInputStream(img)); // joga a imagem em um buffer de bytes
                ImageIcon icone = new ImageIcon(imagem);//Converte os bytes da imagem em um objeto icone
                              
                /* o código abaixo iguala o tamanho da imagem com o tamanho do Jlabel */
                Icon FotoBco;
                FotoBco = new ImageIcon(icone.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(),Image.SCALE_SMOOTH));
                lblFoto.setIcon ( FotoBco ); // coloca a imagem no JLabel
                /* Código que traz o arquivo de imagem no formato bytes do banco de dados  */
            } else {
                JOptionPane.showMessageDialog(null, "Registro não encontrado!");
                this.textcpf.grabFocus();
            }

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Erro ao navegar na Jtable usuários! ");
        } catch (IOException ex) {
            Logger.getLogger(FormCli.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

    }//GEN-LAST:event_jTable1KeyPressed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFotoActionPerformed


    private void btnFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFotoMouseClicked

        /**
         * **CAIXA DE DIALOGO PARA BUSCAR O CAMINHO DA IMAGEM******
         */
        String path = null;   // armazena o caminho da imagem em path
        try {
            JFileChooser filechooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("image files", "pnj", "jpg", "bmp");
            filechooser.setFileFilter(filter);
            filechooser.setCurrentDirectory(new File("."));
            int result = filechooser.showOpenDialog(this);
            
            if (result == JFileChooser.APPROVE_OPTION)
            {
               path = filechooser.getSelectedFile().getAbsolutePath();

                  this.foto = new FileInputStream( filechooser.getSelectedFile() );
                  this.tamanho = (int) filechooser.getSelectedFile().length();
                
            } else if (result == JFileChooser.CANCEL_OPTION) {
                return;
            }
            /**
             * **CAIXA DE DIALOGO PARA BUSCAR O CAMINHO DA IMAGEM******
             */


            /*
              Para imagens no disco rigito com path absoluto use
              ImageIcon  imagem = new ImageIcon( "c:\temp\Figura.jpg" );
            
              Para imagens dentro do NetBeans com path relativo use 
              ImageIcon   imagem = new ImageIcon(getClass().getResource("/imagens/Figura.jfif"));  
            */

            ImageIcon  imagem = new ImageIcon( path );  // Use este comando para path absoluto      
            Image modelImagem = imagem.getImage();
            Image ModelEscalas = modelImagem.getScaledInstance(this.lblFoto.getWidth(), this.lblFoto.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ImagemAutoSize = new ImageIcon(ModelEscalas);
            this.lblFoto.setIcon ( null );
            this.lblFoto.setIcon(ImagemAutoSize);
            
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btnFotoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* St the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btngravar;
    private javax.swing.JButton btnnovo;
    private javax.swing.JComboBox<String> cmbnivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JPasswordField textSenha;
    private javax.swing.JTextField textcelular;
    private javax.swing.JTextField textcpf;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textnome;
    // End of variables declaration//GEN-END:variables
}
